//#line 2 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the raytracer_pkg package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __raytracer_pkg__LIDAR_POSECONFIG_H__
#define __raytracer_pkg__LIDAR_POSECONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace raytracer_pkg
{
  class lidar_poseConfigStatics;

  class lidar_poseConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      virtual ~AbstractParamDescription() = default;

      virtual void clamp(lidar_poseConfig &config, const lidar_poseConfig &max, const lidar_poseConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const lidar_poseConfig &config1, const lidar_poseConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, lidar_poseConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const lidar_poseConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, lidar_poseConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const lidar_poseConfig &config) const = 0;
      virtual void getValue(const lidar_poseConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T lidar_poseConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T lidar_poseConfig::* field;

      virtual void clamp(lidar_poseConfig &config, const lidar_poseConfig &max, const lidar_poseConfig &min) const override
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const lidar_poseConfig &config1, const lidar_poseConfig &config2) const override
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, lidar_poseConfig &config) const override
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const lidar_poseConfig &config) const override
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, lidar_poseConfig &config) const override
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const lidar_poseConfig &config) const override
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const lidar_poseConfig &config, boost::any &val) const override
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      virtual ~AbstractGroupDescription() = default;

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, lidar_poseConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, lidar_poseConfig &top) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const override
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<lidar_poseConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(lidar_poseConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("LiDAR1_x"==(*_i)->name){LiDAR1_x = boost::any_cast<double>(val);}
        if("LiDAR1_y"==(*_i)->name){LiDAR1_y = boost::any_cast<double>(val);}
        if("LiDAR1_z"==(*_i)->name){LiDAR1_z = boost::any_cast<double>(val);}
        if("LiDAR1_roll"==(*_i)->name){LiDAR1_roll = boost::any_cast<int>(val);}
        if("LiDAR1_pitch"==(*_i)->name){LiDAR1_pitch = boost::any_cast<int>(val);}
        if("LiDAR1_yaw"==(*_i)->name){LiDAR1_yaw = boost::any_cast<int>(val);}
        if("LiDAR2_x"==(*_i)->name){LiDAR2_x = boost::any_cast<double>(val);}
        if("LiDAR2_y"==(*_i)->name){LiDAR2_y = boost::any_cast<double>(val);}
        if("LiDAR2_z"==(*_i)->name){LiDAR2_z = boost::any_cast<double>(val);}
        if("LiDAR2_roll"==(*_i)->name){LiDAR2_roll = boost::any_cast<int>(val);}
        if("LiDAR2_pitch"==(*_i)->name){LiDAR2_pitch = boost::any_cast<int>(val);}
        if("LiDAR2_yaw"==(*_i)->name){LiDAR2_yaw = boost::any_cast<int>(val);}
        if("LiDAR3_x"==(*_i)->name){LiDAR3_x = boost::any_cast<double>(val);}
        if("LiDAR3_y"==(*_i)->name){LiDAR3_y = boost::any_cast<double>(val);}
        if("LiDAR3_z"==(*_i)->name){LiDAR3_z = boost::any_cast<double>(val);}
        if("LiDAR3_roll"==(*_i)->name){LiDAR3_roll = boost::any_cast<int>(val);}
        if("LiDAR3_pitch"==(*_i)->name){LiDAR3_pitch = boost::any_cast<int>(val);}
        if("LiDAR3_yaw"==(*_i)->name){LiDAR3_yaw = boost::any_cast<int>(val);}
      }
    }

    double LiDAR1_x;
double LiDAR1_y;
double LiDAR1_z;
int LiDAR1_roll;
int LiDAR1_pitch;
int LiDAR1_yaw;
double LiDAR2_x;
double LiDAR2_y;
double LiDAR2_z;
int LiDAR2_roll;
int LiDAR2_pitch;
int LiDAR2_yaw;
double LiDAR3_x;
double LiDAR3_y;
double LiDAR3_z;
int LiDAR3_roll;
int LiDAR3_pitch;
int LiDAR3_yaw;

    bool state;
    std::string name;

    
}groups;



//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double LiDAR1_x;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double LiDAR1_y;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double LiDAR1_z;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int LiDAR1_roll;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int LiDAR1_pitch;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int LiDAR1_yaw;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double LiDAR2_x;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double LiDAR2_y;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double LiDAR2_z;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int LiDAR2_roll;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int LiDAR2_pitch;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int LiDAR2_yaw;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double LiDAR3_x;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double LiDAR3_y;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double LiDAR3_z;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int LiDAR3_roll;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int LiDAR3_pitch;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int LiDAR3_yaw;
//#line 231 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("lidar_poseConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const lidar_poseConfig &__max__ = __getMax__();
      const lidar_poseConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const lidar_poseConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const lidar_poseConfig &__getDefault__();
    static const lidar_poseConfig &__getMax__();
    static const lidar_poseConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const lidar_poseConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void lidar_poseConfig::ParamDescription<std::string>::clamp(lidar_poseConfig &config, const lidar_poseConfig &max, const lidar_poseConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class lidar_poseConfigStatics
  {
    friend class lidar_poseConfig;

    lidar_poseConfigStatics()
    {
lidar_poseConfig::GroupDescription<lidar_poseConfig::DEFAULT, lidar_poseConfig> Default("Default", "", 0, 0, true, &lidar_poseConfig::groups);
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.LiDAR1_x = -10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.LiDAR1_x = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.LiDAR1_x = 0.5;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(lidar_poseConfig::AbstractParamDescriptionConstPtr(new lidar_poseConfig::ParamDescription<double>("LiDAR1_x", "double", 0, "x-coordinate of LiDAR1", "", &lidar_poseConfig::LiDAR1_x)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(lidar_poseConfig::AbstractParamDescriptionConstPtr(new lidar_poseConfig::ParamDescription<double>("LiDAR1_x", "double", 0, "x-coordinate of LiDAR1", "", &lidar_poseConfig::LiDAR1_x)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.LiDAR1_y = -10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.LiDAR1_y = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.LiDAR1_y = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(lidar_poseConfig::AbstractParamDescriptionConstPtr(new lidar_poseConfig::ParamDescription<double>("LiDAR1_y", "double", 0, "x-coordinate of LiDAR1", "", &lidar_poseConfig::LiDAR1_y)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(lidar_poseConfig::AbstractParamDescriptionConstPtr(new lidar_poseConfig::ParamDescription<double>("LiDAR1_y", "double", 0, "x-coordinate of LiDAR1", "", &lidar_poseConfig::LiDAR1_y)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.LiDAR1_z = -10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.LiDAR1_z = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.LiDAR1_z = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(lidar_poseConfig::AbstractParamDescriptionConstPtr(new lidar_poseConfig::ParamDescription<double>("LiDAR1_z", "double", 0, "x-coordinate of LiDAR1", "", &lidar_poseConfig::LiDAR1_z)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(lidar_poseConfig::AbstractParamDescriptionConstPtr(new lidar_poseConfig::ParamDescription<double>("LiDAR1_z", "double", 0, "x-coordinate of LiDAR1", "", &lidar_poseConfig::LiDAR1_z)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.LiDAR1_roll = -90;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.LiDAR1_roll = 90;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.LiDAR1_roll = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(lidar_poseConfig::AbstractParamDescriptionConstPtr(new lidar_poseConfig::ParamDescription<int>("LiDAR1_roll", "int", 0, "x-coordinate of LiDAR1", "", &lidar_poseConfig::LiDAR1_roll)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(lidar_poseConfig::AbstractParamDescriptionConstPtr(new lidar_poseConfig::ParamDescription<int>("LiDAR1_roll", "int", 0, "x-coordinate of LiDAR1", "", &lidar_poseConfig::LiDAR1_roll)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.LiDAR1_pitch = -90;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.LiDAR1_pitch = 90;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.LiDAR1_pitch = 2;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(lidar_poseConfig::AbstractParamDescriptionConstPtr(new lidar_poseConfig::ParamDescription<int>("LiDAR1_pitch", "int", 0, "x-coordinate of LiDAR1", "", &lidar_poseConfig::LiDAR1_pitch)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(lidar_poseConfig::AbstractParamDescriptionConstPtr(new lidar_poseConfig::ParamDescription<int>("LiDAR1_pitch", "int", 0, "x-coordinate of LiDAR1", "", &lidar_poseConfig::LiDAR1_pitch)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.LiDAR1_yaw = -90;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.LiDAR1_yaw = 90;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.LiDAR1_yaw = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(lidar_poseConfig::AbstractParamDescriptionConstPtr(new lidar_poseConfig::ParamDescription<int>("LiDAR1_yaw", "int", 0, "x-coordinate of LiDAR1", "", &lidar_poseConfig::LiDAR1_yaw)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(lidar_poseConfig::AbstractParamDescriptionConstPtr(new lidar_poseConfig::ParamDescription<int>("LiDAR1_yaw", "int", 0, "x-coordinate of LiDAR1", "", &lidar_poseConfig::LiDAR1_yaw)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.LiDAR2_x = -10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.LiDAR2_x = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.LiDAR2_x = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(lidar_poseConfig::AbstractParamDescriptionConstPtr(new lidar_poseConfig::ParamDescription<double>("LiDAR2_x", "double", 0, "x-coordinate of LiDAR2", "", &lidar_poseConfig::LiDAR2_x)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(lidar_poseConfig::AbstractParamDescriptionConstPtr(new lidar_poseConfig::ParamDescription<double>("LiDAR2_x", "double", 0, "x-coordinate of LiDAR2", "", &lidar_poseConfig::LiDAR2_x)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.LiDAR2_y = -10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.LiDAR2_y = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.LiDAR2_y = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(lidar_poseConfig::AbstractParamDescriptionConstPtr(new lidar_poseConfig::ParamDescription<double>("LiDAR2_y", "double", 0, "x-coordinate of LiDAR2", "", &lidar_poseConfig::LiDAR2_y)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(lidar_poseConfig::AbstractParamDescriptionConstPtr(new lidar_poseConfig::ParamDescription<double>("LiDAR2_y", "double", 0, "x-coordinate of LiDAR2", "", &lidar_poseConfig::LiDAR2_y)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.LiDAR2_z = -10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.LiDAR2_z = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.LiDAR2_z = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(lidar_poseConfig::AbstractParamDescriptionConstPtr(new lidar_poseConfig::ParamDescription<double>("LiDAR2_z", "double", 0, "x-coordinate of LiDAR2", "", &lidar_poseConfig::LiDAR2_z)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(lidar_poseConfig::AbstractParamDescriptionConstPtr(new lidar_poseConfig::ParamDescription<double>("LiDAR2_z", "double", 0, "x-coordinate of LiDAR2", "", &lidar_poseConfig::LiDAR2_z)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.LiDAR2_roll = -90;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.LiDAR2_roll = 90;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.LiDAR2_roll = -5;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(lidar_poseConfig::AbstractParamDescriptionConstPtr(new lidar_poseConfig::ParamDescription<int>("LiDAR2_roll", "int", 0, "x-coordinate of LiDAR2", "", &lidar_poseConfig::LiDAR2_roll)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(lidar_poseConfig::AbstractParamDescriptionConstPtr(new lidar_poseConfig::ParamDescription<int>("LiDAR2_roll", "int", 0, "x-coordinate of LiDAR2", "", &lidar_poseConfig::LiDAR2_roll)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.LiDAR2_pitch = -90;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.LiDAR2_pitch = 90;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.LiDAR2_pitch = 2;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(lidar_poseConfig::AbstractParamDescriptionConstPtr(new lidar_poseConfig::ParamDescription<int>("LiDAR2_pitch", "int", 0, "x-coordinate of LiDAR2", "", &lidar_poseConfig::LiDAR2_pitch)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(lidar_poseConfig::AbstractParamDescriptionConstPtr(new lidar_poseConfig::ParamDescription<int>("LiDAR2_pitch", "int", 0, "x-coordinate of LiDAR2", "", &lidar_poseConfig::LiDAR2_pitch)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.LiDAR2_yaw = -90;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.LiDAR2_yaw = 90;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.LiDAR2_yaw = 10;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(lidar_poseConfig::AbstractParamDescriptionConstPtr(new lidar_poseConfig::ParamDescription<int>("LiDAR2_yaw", "int", 0, "x-coordinate of LiDAR2", "", &lidar_poseConfig::LiDAR2_yaw)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(lidar_poseConfig::AbstractParamDescriptionConstPtr(new lidar_poseConfig::ParamDescription<int>("LiDAR2_yaw", "int", 0, "x-coordinate of LiDAR2", "", &lidar_poseConfig::LiDAR2_yaw)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.LiDAR3_x = -10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.LiDAR3_x = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.LiDAR3_x = 0.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(lidar_poseConfig::AbstractParamDescriptionConstPtr(new lidar_poseConfig::ParamDescription<double>("LiDAR3_x", "double", 0, "x-coordinate of LiDAR3", "", &lidar_poseConfig::LiDAR3_x)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(lidar_poseConfig::AbstractParamDescriptionConstPtr(new lidar_poseConfig::ParamDescription<double>("LiDAR3_x", "double", 0, "x-coordinate of LiDAR3", "", &lidar_poseConfig::LiDAR3_x)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.LiDAR3_y = -10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.LiDAR3_y = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.LiDAR3_y = -1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(lidar_poseConfig::AbstractParamDescriptionConstPtr(new lidar_poseConfig::ParamDescription<double>("LiDAR3_y", "double", 0, "x-coordinate of LiDAR3", "", &lidar_poseConfig::LiDAR3_y)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(lidar_poseConfig::AbstractParamDescriptionConstPtr(new lidar_poseConfig::ParamDescription<double>("LiDAR3_y", "double", 0, "x-coordinate of LiDAR3", "", &lidar_poseConfig::LiDAR3_y)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.LiDAR3_z = -10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.LiDAR3_z = 10.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.LiDAR3_z = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(lidar_poseConfig::AbstractParamDescriptionConstPtr(new lidar_poseConfig::ParamDescription<double>("LiDAR3_z", "double", 0, "x-coordinate of LiDAR3", "", &lidar_poseConfig::LiDAR3_z)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(lidar_poseConfig::AbstractParamDescriptionConstPtr(new lidar_poseConfig::ParamDescription<double>("LiDAR3_z", "double", 0, "x-coordinate of LiDAR3", "", &lidar_poseConfig::LiDAR3_z)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.LiDAR3_roll = -90;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.LiDAR3_roll = 90;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.LiDAR3_roll = 5;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(lidar_poseConfig::AbstractParamDescriptionConstPtr(new lidar_poseConfig::ParamDescription<int>("LiDAR3_roll", "int", 0, "x-coordinate of LiDAR3", "", &lidar_poseConfig::LiDAR3_roll)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(lidar_poseConfig::AbstractParamDescriptionConstPtr(new lidar_poseConfig::ParamDescription<int>("LiDAR3_roll", "int", 0, "x-coordinate of LiDAR3", "", &lidar_poseConfig::LiDAR3_roll)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.LiDAR3_pitch = -90;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.LiDAR3_pitch = 90;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.LiDAR3_pitch = 2;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(lidar_poseConfig::AbstractParamDescriptionConstPtr(new lidar_poseConfig::ParamDescription<int>("LiDAR3_pitch", "int", 0, "x-coordinate of LiDAR3", "", &lidar_poseConfig::LiDAR3_pitch)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(lidar_poseConfig::AbstractParamDescriptionConstPtr(new lidar_poseConfig::ParamDescription<int>("LiDAR3_pitch", "int", 0, "x-coordinate of LiDAR3", "", &lidar_poseConfig::LiDAR3_pitch)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.LiDAR3_yaw = -90;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.LiDAR3_yaw = 90;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.LiDAR3_yaw = -10;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(lidar_poseConfig::AbstractParamDescriptionConstPtr(new lidar_poseConfig::ParamDescription<int>("LiDAR3_yaw", "int", 0, "x-coordinate of LiDAR3", "", &lidar_poseConfig::LiDAR3_yaw)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(lidar_poseConfig::AbstractParamDescriptionConstPtr(new lidar_poseConfig::ParamDescription<int>("LiDAR3_yaw", "int", 0, "x-coordinate of LiDAR3", "", &lidar_poseConfig::LiDAR3_yaw)));
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(lidar_poseConfig::AbstractGroupDescriptionConstPtr(new lidar_poseConfig::GroupDescription<lidar_poseConfig::DEFAULT, lidar_poseConfig>(Default)));
//#line 369 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<lidar_poseConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<lidar_poseConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<lidar_poseConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    lidar_poseConfig __max__;
    lidar_poseConfig __min__;
    lidar_poseConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const lidar_poseConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static lidar_poseConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &lidar_poseConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const lidar_poseConfig &lidar_poseConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const lidar_poseConfig &lidar_poseConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const lidar_poseConfig &lidar_poseConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<lidar_poseConfig::AbstractParamDescriptionConstPtr> &lidar_poseConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<lidar_poseConfig::AbstractGroupDescriptionConstPtr> &lidar_poseConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const lidar_poseConfigStatics *lidar_poseConfig::__get_statics__()
  {
    const static lidar_poseConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = lidar_poseConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __LIDAR_POSERECONFIGURATOR_H__
