// Generated by gencpp from file raytracer_pkg/represent_plane.msg
// DO NOT EDIT!


#ifndef RAYTRACER_PKG_MESSAGE_REPRESENT_PLANE_H
#define RAYTRACER_PKG_MESSAGE_REPRESENT_PLANE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Vector3.h>

namespace raytracer_pkg
{
template <class ContainerAllocator>
struct represent_plane_
{
  typedef represent_plane_<ContainerAllocator> Type;

  represent_plane_()
    : header()
    , point()
    , normal()  {
    }
  represent_plane_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , point(_alloc)
    , normal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _point_type;
  _point_type point;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _normal_type;
  _normal_type normal;





  typedef boost::shared_ptr< ::raytracer_pkg::represent_plane_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::raytracer_pkg::represent_plane_<ContainerAllocator> const> ConstPtr;

}; // struct represent_plane_

typedef ::raytracer_pkg::represent_plane_<std::allocator<void> > represent_plane;

typedef boost::shared_ptr< ::raytracer_pkg::represent_plane > represent_planePtr;
typedef boost::shared_ptr< ::raytracer_pkg::represent_plane const> represent_planeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::raytracer_pkg::represent_plane_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::raytracer_pkg::represent_plane_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::raytracer_pkg::represent_plane_<ContainerAllocator1> & lhs, const ::raytracer_pkg::represent_plane_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.point == rhs.point &&
    lhs.normal == rhs.normal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::raytracer_pkg::represent_plane_<ContainerAllocator1> & lhs, const ::raytracer_pkg::represent_plane_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace raytracer_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::raytracer_pkg::represent_plane_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::raytracer_pkg::represent_plane_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::raytracer_pkg::represent_plane_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::raytracer_pkg::represent_plane_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::raytracer_pkg::represent_plane_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::raytracer_pkg::represent_plane_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::raytracer_pkg::represent_plane_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e6dad39e8527110ab026c6017616f37b";
  }

  static const char* value(const ::raytracer_pkg::represent_plane_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe6dad39e8527110aULL;
  static const uint64_t static_value2 = 0xb026c6017616f37bULL;
};

template<class ContainerAllocator>
struct DataType< ::raytracer_pkg::represent_plane_<ContainerAllocator> >
{
  static const char* value()
  {
    return "raytracer_pkg/represent_plane";
  }

  static const char* value(const ::raytracer_pkg::represent_plane_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::raytracer_pkg::represent_plane_<ContainerAllocator> >
{
  static const char* value()
  {
    return "  Header header\n"
"  geometry_msgs/Point point\n"
"  geometry_msgs/Vector3 normal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::raytracer_pkg::represent_plane_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::raytracer_pkg::represent_plane_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.point);
      stream.next(m.normal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct represent_plane_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::raytracer_pkg::represent_plane_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::raytracer_pkg::represent_plane_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "point: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.point);
    s << indent << "normal: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.normal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RAYTRACER_PKG_MESSAGE_REPRESENT_PLANE_H
