// Generated by gencpp from file raytracer_pkg/represent_plane.msg
// DO NOT EDIT!


#ifndef RAYTRACER_PKG_MESSAGE_REPRESENT_PLANE_H
#define RAYTRACER_PKG_MESSAGE_REPRESENT_PLANE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Vector3.h>

namespace raytracer_pkg
{
template <class ContainerAllocator>
struct represent_plane_
{
  typedef represent_plane_<ContainerAllocator> Type;

  represent_plane_()
    : header()
    , corner1()
    , corner2()
    , corner3()
    , corner4()
    , normal()  {
    }
  represent_plane_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , corner1(_alloc)
    , corner2(_alloc)
    , corner3(_alloc)
    , corner4(_alloc)
    , normal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _corner1_type;
  _corner1_type corner1;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _corner2_type;
  _corner2_type corner2;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _corner3_type;
  _corner3_type corner3;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _corner4_type;
  _corner4_type corner4;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _normal_type;
  _normal_type normal;





  typedef boost::shared_ptr< ::raytracer_pkg::represent_plane_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::raytracer_pkg::represent_plane_<ContainerAllocator> const> ConstPtr;

}; // struct represent_plane_

typedef ::raytracer_pkg::represent_plane_<std::allocator<void> > represent_plane;

typedef boost::shared_ptr< ::raytracer_pkg::represent_plane > represent_planePtr;
typedef boost::shared_ptr< ::raytracer_pkg::represent_plane const> represent_planeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::raytracer_pkg::represent_plane_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::raytracer_pkg::represent_plane_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::raytracer_pkg::represent_plane_<ContainerAllocator1> & lhs, const ::raytracer_pkg::represent_plane_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.corner1 == rhs.corner1 &&
    lhs.corner2 == rhs.corner2 &&
    lhs.corner3 == rhs.corner3 &&
    lhs.corner4 == rhs.corner4 &&
    lhs.normal == rhs.normal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::raytracer_pkg::represent_plane_<ContainerAllocator1> & lhs, const ::raytracer_pkg::represent_plane_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace raytracer_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::raytracer_pkg::represent_plane_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::raytracer_pkg::represent_plane_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::raytracer_pkg::represent_plane_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::raytracer_pkg::represent_plane_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::raytracer_pkg::represent_plane_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::raytracer_pkg::represent_plane_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::raytracer_pkg::represent_plane_<ContainerAllocator> >
{
  static const char* value()
  {
    return "29f9b3d844ed52a85b0f1b939894669b";
  }

  static const char* value(const ::raytracer_pkg::represent_plane_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x29f9b3d844ed52a8ULL;
  static const uint64_t static_value2 = 0x5b0f1b939894669bULL;
};

template<class ContainerAllocator>
struct DataType< ::raytracer_pkg::represent_plane_<ContainerAllocator> >
{
  static const char* value()
  {
    return "raytracer_pkg/represent_plane";
  }

  static const char* value(const ::raytracer_pkg::represent_plane_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::raytracer_pkg::represent_plane_<ContainerAllocator> >
{
  static const char* value()
  {
    return "  Header header\n"
"  geometry_msgs/Point corner1\n"
"  geometry_msgs/Point corner2\n"
"  geometry_msgs/Point corner3\n"
"  geometry_msgs/Point corner4\n"
"  geometry_msgs/Vector3 normal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::raytracer_pkg::represent_plane_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::raytracer_pkg::represent_plane_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.corner1);
      stream.next(m.corner2);
      stream.next(m.corner3);
      stream.next(m.corner4);
      stream.next(m.normal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct represent_plane_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::raytracer_pkg::represent_plane_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::raytracer_pkg::represent_plane_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "corner1: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.corner1);
    s << indent << "corner2: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.corner2);
    s << indent << "corner3: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.corner3);
    s << indent << "corner4: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.corner4);
    s << indent << "normal: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.normal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RAYTRACER_PKG_MESSAGE_REPRESENT_PLANE_H
